### ISSUE TITLE
Repo for all jQuery plugins may sound odd

### ISSUE THREAD

**Issue by RohanSakhale** [sachingadagi/JqueryPlugin-s-#2]
If you want your plugins to be used by people more often, then instead of keeping a single repo, every plugin if placed in individual repo may help in better way for downloading as well as people may fork in simpler way if they want to contribute anything in there.

**Comment by sachingadagi** [comment]
hi Rohan,
As per you suggestion I have created a new Repo with same files . You can visit it here http://goo.gl/4nrxQm .
Thank you. :)

**Comment by RohanSakhale** [comment]
:+1:
